language: generic

sudo: required

services:
  - docker

before_install:
- mv "$STACK_YAML" stack.yaml
- docker pull "taffybar/taffybar:latest-$STACK_YAML"

matrix:
  include:
  - env: STACK_YAML=stack-7.10.yaml
  - env: STACK_YAML=stack-8.0.yaml
  - env: STACK_YAML=stack-8.2.yaml

install:
- docker build --target taffyenv --cache-from "taffybar/taffybar:latest-$STACK_YAML" .

script:
- docker build --target taffybuild --cache-from "taffybar/taffybar:latest-$STACK_YAML" .
