language: generic

sudo: required

services:
  - docker

before_install:
- docker pull "taffybar/taffybar:latest-$STACK_YAML"

matrix:
  include:
  # TODO renabled 7.10 and quickstart build
  # - env: STACK_YAML=stack-7.10.yaml
  - env: STACK_YAML=stack-8.0.yaml
  - env: STACK_YAML=stack-8.2.yaml

script:
- docker build --cache-from "taffybar/taffybar:latest-$STACK_YAML" --build-arg STACK_YAML="$STACK_YAML" .
