language: generic
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- stack install gtk2hs-buildtools

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - libgtk-3-dev
          - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - libgtk-3-dev
          - ghc-7.10.3
  - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - libgtk-3-dev
          - ghc-8.0.2
  - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.yaml
    before_install:
      - mkdir -p ~/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - export PATH=/opt/ghc/$GHCVER/bin:$PATH
      - stack setup --upgrade-cabal
      - stack install gtk2hs-buildtools
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - libgtk-3-dev
          - ghc-8.2.2
  - env: BUILD_TYPE='Test quick start'
    addons:
      apt:
        packages:
          - libgtk-3-dev
    sudo: required
    script:
      - ./quick-start.sh

install:
- stack --no-terminal --install-ghc $ARGS test --bench --dry-run || ( \
    stack --no-terminal $ARGS build cabal-install && \
    stack --no-terminal $ARGS solver --update-config)
# Build the dependencies
- stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
 - stack --no-terminal --install-ghc build
